"""New Migration

Revision ID: 15439fa05508
Revises: 941c9c9eb3ef
Create Date: 2021-07-23 16:11:50.053469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15439fa05508'
down_revision = '941c9c9eb3ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
